#======================<开发环境配置>=========================
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/web?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
  redis:
    password: 1qaz2wsx
    port: 6379
    host: 127.0.0.1
    database: 1
    jedis:
      pool:
        max-active: 20
        max-idle: 20
        max-wait: -1ms
        min-idle: 1
    timeout: 5000ms

